force-app/main/default/objects/EventActivity__e/EventActivity__e.object-meta.xml
<CustomObject>
    <label>Event Activity</label>
    <pluralLabel>Event Activities</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventActivity__e/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventActivity__e/fields/FirstReplayID__c.field-meta.xml
<CustomField>
    <fullName>FirstReplayID__c</fullName>
    <label>First replay ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventActivity__e/fields/HandlerClassName__c.field-meta.xml
<CustomField>
    <fullName>HandlerClassName__c</fullName>
    <label>Handler Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventActivity__e/fields/IsCDC__c.field-meta.xml
<CustomField>
    <fullName>IsCDC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If is true means that it is a event from change data capture</description>
    <label>Is CDC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventActivity__e/fields/LastReplayID__c.field-meta.xml
<CustomField>
    <fullName>LastReplayID__c</fullName>
    <label>Last replay ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventActivityBuilder.cls
public inherited sharing class EventActivityBuilder {

    private EventActivity__e activity;

    public EventActivityBuilder() {
        this.activity = new EventActivity__e();
    }

    public EventActivityBuilder isChangeDataCapture() {
        this.activity.IsCDC__c = true;
        return this;
    }

    public EventActivityBuilder handlerNamedAs(String handlerName) {
        this.activity.HandlerClassName__c = handlerName;
        return this;
    }

    public EventActivityBuilder forEvents(EventCollection events){
        if (events.all().isEmpty()) {
            return this;
        }
        this.activity.EventType__c = String.valueOf(events.all().get(0).getSObjectType());
        this.activity.FirstReplayID__c = events.getFirstReplayId();
        this.activity.LastReplayID__c = events.getLastReplayId();
        return this;
    }

    public EventActivityBuilder throwedException(Exception ex){
        this.activity.ErrorMessage__c = ex.getMessage();
        this.activity.Type__c = ex.getTypeName();
        return this;
    }

    public EventActivity__e build(){
        return this.activity;
    }

}